version: '3.0'

networks:
  hackathon_becoder:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5436:5432"
    env_file:
      - .env
    networks:
      - hackathon_becoder
    volumes:
      - db-data:/var/lib/postgresql/data